name: CI/CD Pipeline for Render Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # O ajusta a la versión que uses

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest   # O el comando que uses para correr tests
      continue-on-error: false  # Si falla, el workflow se detiene

    - name: Trigger Render deploy
      if: success()  # Solo si los pasos anteriores pasaron
      run: |
        curl -X POST https://api.render.com/deploy/srv-d0sbmb3e5dus73ekmq7g \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
