name: CI/CD Pipeline for Render Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: localhost
      DB_PORT: 5432
      SECRET_KEY: dummy_secret_key_for_ci
      DEBUG: '1'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          echo "Waiting for postgres..."
          sleep 2
        done

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      id: test_step
      run: |
        pytest tests/

    - name: Trigger Render deploy
      if: steps.test_step.outcome == 'success'
      run: |
        curl -X POST https://api.render.com/deploy/srv-d0sbmb3e5dus73ekmq7g \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
