name: CI/CD Pipeline for Render Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django

    - name: Run tests
      id: test_step
      run: |
        pytest tests/

    - name: Trigger Render deploy
      if: steps.test_step.outcome == 'success'
      run: |
        curl -X POST https://api.render.com/deploy/srv-d0sbmb3e5dus73ekmq7g \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
